# @package _group_
_target_: pytorch_lightning.Trainer
accelerator: auto
accumulate_grad_batches: 1
auto_scale_batch_size: False
auto_lr_find: False
benchmark: False
deterministic: False
check_val_every_n_epoch: 1
devices: auto
detect_anomaly: False
enable_checkpointing: True
enable_model_summary: True
enable_progress_bar: True
fast_dev_run: False
gradient_clip_val: 0
gradient_clip_algorithm: norm
limit_predict_batches: 1.0
limit_test_batches: 1.0
limit_train_batches: 1.0
limit_val_batches: 1.0
log_every_n_steps: 50
max_epochs: 1000
max_steps: -1
max_time: null
min_epochs: 1
min_steps: null
move_metrics_to_cpu: False
multiple_trainloader_mode: max_size_cycle
num_nodes: 1
num_sanity_val_steps: 2
overfit_batches: 0.0
precision: 32
profiler: null
reload_dataloaders_every_n_epochs: 0
replace_sampler_ddp: True
strategy: null
sync_batchnorm: False
track_grad_norm: -1
val_check_interval: 1.0
